### ISSUE TITLE
You're missing the critical information about the API endpoint address!

### ISSUE THREAD

**Issue by fake-name** [oxguy3/patreon-api#2]
I'm doing some hacking with the patreon API, and you're missing the fact that the API endpoint is `api.patreon.com`. 

I spent a bit of time sending requests to the normal `www.patreon.com` domain and trying to futz with the `Accept` and `Content-Type` `GET` headers to get an API response before I realized what was going on.

**Comment by hayleox** [comment]
Haha whoops, just fixed this!
